name = "StencilInterpolation"
uuid = "bfc67a74-a27b-455a-b689-c68d3806f53b"
authors = ["albert-de-montserrat <58044444+albert-de-montserrat@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
